apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: {{ .Values.airflow.version }}
    helm:
      values: |
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
          jobAnnotations:
            "argocd.argoproj.io/hook": PostSync
            "argocd.argoproj.io/hook-delete-policy": HookSucceeded
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
          jobAnnotations:
              "argocd.argoproj.io/hook": Sync
        useStandardNaming: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
